# Generated by Django 6.1.1 on 2026-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='Togo', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
