# Generated by Django 6.1.1 on 2026-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('pending', 'En attente de validation'), ('suspended', 'Suspendu'), ('rejected', 'Refusé')], default='active', max_length=20),
        ),
    ]
