# Generated by Django 6.1.2 on 2026-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_user_lat_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_diagnostics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_new_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_order_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_stock_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_visible',
            field=models.BooleanField(default=True),
        ),
    ]
