# Generated by Django 6.1.1 on 2026-09-14 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('user_label', models.CharField(blank=True, default='', max_length=150)),
                ('type', models.CharField(choices=[('auth', 'Authentification'), ('register', 'Inscription'), ('diagnostic', 'Diagnostic'), ('assistant', 'Assistant IA'), ('product', 'Produit'), ('request', 'Demande'), ('admin', 'Administration')], default='admin', max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
