# Generated by Django 6.1.2 on 2026-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_validate_suppliers', models.BooleanField(default=False)),
                ('confidence_threshold', models.PositiveSmallIntegerField(default=75)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
    ]
