# Generated by Django 6.1.2 on 2026-10-08 20:50

import django.db.models.deletion
import marketplace.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default=marketplace.models._generate_reference, max_length=12, unique=True)),
                ('buyer_name', models.CharField(max_length=150)),
                ('supplier_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('preparing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=12)),
                ('subtotal', models.PositiveIntegerField(help_text="Total payé par l'acheteur (FCFA)")),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('commission_amount', models.PositiveIntegerField(default=0, help_text='Commission AgriRisk (FCFA)')),
                ('supplier_amount', models.PositiveIntegerField(default=0, help_text='Montant net dû au fournisseur (FCFA)')),
                ('delivery_method', models.CharField(choices=[('pickup', 'Retrait chez le fournisseur'), ('delivery', 'Livraison')], default='pickup', max_length=10)),
                ('delivery_address', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('payout_status', models.CharField(choices=[('none', 'Non dû'), ('available', 'À reverser'), ('paid', 'Reversé')], default='none', max_length=10)),
                ('refund_status', models.CharField(choices=[('none', 'Aucun'), ('needed', 'Remboursement à faire'), ('done', 'Remboursée')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='marketplace.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='fedapay', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('approved', 'Approuvé'), ('declined', 'Refusé'), ('canceled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=10)),
                ('payment_url', models.URLField(blank=True, default='', max_length=500)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('tmoney', 'T-Money (Togocom)'), ('flooz', 'Flooz (Moov Africa)'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('orange', 'Orange Money'), ('wave', 'Wave'), ('other', 'Autre')], default='tmoney', max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('account_name', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
