# Generated by Django 6.1.1 on 2026-09-08 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('culture', 'Culture'), ('animal', 'Animal')], max_length=10)),
                ('image', models.ImageField(upload_to='diagnostics/')),
                ('disease_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé'), ('Critique', 'Critique')], max_length=10)),
                ('causes', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('treatment', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
